"""Add datatime to item table.

Revision ID: 1d9de5a45ff0
Revises: c2af5c1f5e4b
Create Date: 2023-04-23 14:35:58.889528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9de5a45ff0'
down_revision = 'c2af5c1f5e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
